### ISSUE TITLE
App uploads empy to Testflight

### ISSUE THREAD

**Issue by mastersam92** [bitrise-io/steps-deploy-to-itunesconnect-shenzhen#4]
App uploads to testflight, app( compiled version ) appears in t.f, but, app size is 0kb and it's can't be downloaded in t.f( it tells about error ).

In workflow, step 'deploy to iTunesConnect/..' right after 'xcode archive & export for ios'.
Step with 'xcode archive & export for ios' results with correct app some correct size( about 10mb ), but, step 'deploy to iTunesConnect/..'( ending with success ) upload to t.f, uploads empty app.

**Comment by trapacska** [comment]
Hey @mastersam92 !

Thank you for reporting the issue. I made a note in our internal tracker to check this issue! We'll get back ASAP.

**Comment by viktorbenei** [comment]
@mastersam92 can you please copy paste the related build's bitrise.io URL, so that we can check the logs?

**Comment by godrei** [comment]
Closing as we did not receive a reply - @mastersam92 please let us know if we can help with anything and we'll reopen this issue!
